version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: migrator_pg
    environment:
      POSTGRES_USER: santiago
      POSTGRES_PASSWORD: santiago
      POSTGRES_DB: migrator
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ..
      dockerfile: infra/Dockerfile.api
    container_name: migrator_api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://santiago:santiago@postgres:5432/migrator"
    depends_on:
      - postgres

volumes:
  pgdata:
